baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Aerokube Moon | A Cross Browser Selenium Solution Running in Kubernetes or Openshift Cluster"

enableRobotsTXT = true


# RSS, categories and tags disabled for an easy start
# See configuration options for more details:
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
description = "A cross browser and mobile application testing platform. Fully compatible with Selenium Webdriver. Automated and live testing. Kubernetes and Openshift clusters supported. Runs on your own hardware or in any popular cloud platform: Google Cloud, Amazon Web Services, DigitalOcean, Microsoft Azure and so on."
